spring:
  application:
    name: api-gateway

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:job-scraper-system_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true

  # ActiveMQ Configuration
  activemq:
    broker-url: tcp://${MQ_HOST:localhost}:61616
    user: ${MQ_USER:admin}
    password: ${MQ_PASSWORD:admin}

  # ✉️ Email Configuration (Must be indented under 'spring')
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SYSTEM_EMAIL_ADDRESS:ephadaniel177@gmail.com}
    password: ${SYSTEM_EMAIL_PASSWORD:629177490ipHA++}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${SERVER_PORT:8080}