spring:
  application:
    name: api-gateway

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:job-scraper-system_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true

  # ActiveMQ Configuration
  activemq:
    broker-url: tcp://${MQ_HOST:localhost}:61616
    user: ${MQ_USER:admin}
    password: ${MQ_PASSWORD:admin}

server:
  port: ${SERVER_PORT:8080}